# Generated by Django 2.2.7 on 2020-01-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbfneuronsight',
            old_name='img64',
            new_name='img',
        ),
    ]
