# Generated by Django 2.2.7 on 2020-01-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_collections', '0001_initial'),
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbfneuronsight',
            name='img64',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_related', to='images_collections.ImagesData'),
        ),
    ]
