# Generated by Django 3.0.2 on 2020-03-01 00:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200115_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='rnb',
            fields=[
                ('brain_rnb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='brain.brain')),
                ('index_ready_to_learn', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='brain',
            name='rnb',
        ),
        migrations.CreateModel(
            name='RnbNeuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_knowledge', models.BooleanField()),
                ('hit', models.BooleanField()),
                ('knowledge', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rnb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnb_neuron', to='brain.rnb')),
            ],
        ),
    ]
