# Generated by Django 3.0.2 on 2020-03-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_episodic_memoryproto_episodicmemneuron_group_recognizedindexesepisodicmemory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedindexesepisodicmemory',
            name='episodic_memory',
        ),
        migrations.AddField(
            model_name='episodicmemneuron',
            name='group_EpisodicMemNeuron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodic_mem_neuron', to='brain.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='episodic_memory_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='brain.episodic_memoryproto'),
        ),
        migrations.AddField(
            model_name='recognizedindexesepisodicmemory',
            name='episodic_memory_recognized_indexes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognized_indexes', to='brain.episodic_memoryproto'),
        ),
    ]
