# Generated by Django 3.0.2 on 2020-04-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_auto_20200324_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='episodic_memoryproto',
            new_name='episodic_memory',
        ),
        migrations.RemoveField(
            model_name='brain',
            name='episodic_memory',
        ),
    ]
