# Generated by Django 3.0.2 on 2020-04-14 22:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_auto_20200411_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='indexes_recognized',
        ),
        migrations.AddField(
            model_name='episodic_memory',
            name='indexes_recognized',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
