# Generated by Django 2.2.7 on 2019-12-22 20:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0009_auto_20191113_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='snb_s',
            fields=[
                ('brain_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='snb_s_json', serialize=False, to='brain.projects')),
                ('_state', models.CharField(default='MISS?', max_length=280)),
                ('_index_ready_to_learn', models.IntegerField()),
                ('_last_learned_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RbfNeuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_has_knowledge', models.BooleanField()),
                ('_radius', models.FloatField()),
                ('_degraded', models.FloatField()),
                ('_knowledge', django.contrib.postgres.fields.jsonb.JSONField()),
                ('snb_sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbf_neurons', to='sight_network.snb_s')),
            ],
        ),
        migrations.CreateModel(
            name='IndexRecognize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_recognize', models.IntegerField()),
                ('snb_sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_recognize', to='sight_network.snb_s')),
            ],
        ),
    ]
