# Generated by Django 2.2.7 on 2020-01-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFromNeuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('name_class', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('img64', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
