# Generated by Django 2.2.7 on 2020-01-01 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesfromneuron',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
