# Generated by Django 2.2.7 on 2020-01-01 01:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_rbfneuronsight_img64'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesData',
            new_name='ImagesFromNeuron',
        ),
    ]
