# Generated by Django 2.2.7 on 2020-01-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_collections', '0002_imagesfromneuron_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesfromneuron',
            old_name='other',
            new_name='owner',
        ),
    ]
