# Generated by Django 2.2.7 on 2020-01-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_collections', '0003_auto_20200101_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesfromneuron',
            name='img64',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
