# Generated by Django 3.0.2 on 2020-01-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_collections', '0007_auto_20200101_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesfromneuron',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
