# Generated by Django 2.2.5 on 2019-10-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asd',
        ),
    ]
