# Generated by Django 2.2.5 on 2019-10-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20191024_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_dot',
            field=models.BooleanField(default=False),
        ),
    ]
