# Generated by Django 2.2.5 on 2019-10-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_project_is_dot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_dot',
        ),
    ]
