# Generated by Django 2.2.5 on 2019-10-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_project_is_dot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
