# Generated by Django 3.0.2 on 2020-01-25 02:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images_collections', '0008_auto_20200109_2341'),
        ('brain', '0002_auto_20200115_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_tolerance', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('g_tolerance', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('b_tolerance', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('brain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brain', to='brain.brain')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='images_collections.ImagesFromNeuron')),
            ],
        ),
    ]
