# Generated by Django 3.0.2 on 2020-01-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesettings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
