# Generated by Django 3.0.2 on 2020-01-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200115_1449'),
        ('images_collections', '0008_auto_20200109_2341'),
        ('images_settings', '0002_imagesettings_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettings', to='brain.brain'),
        ),
        migrations.AlterField(
            model_name='imagesettings',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettings', to='images_collections.ImagesFromNeuron'),
        ),
    ]
