# Generated by Django 3.0.2 on 2020-01-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200115_1449'),
        ('images_settings', '0003_auto_20200128_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another', to='brain.brain'),
        ),
    ]
