# Generated by Django 3.0.2 on 2020-01-28 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200115_1449'),
        ('images_collections', '0008_auto_20200109_2341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images_settings', '0004_auto_20200128_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='brain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettingsFromBrain', to='brain.brain'),
        ),
        migrations.AlterField(
            model_name='imagesettings',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettingsFromImage', to='images_collections.ImagesFromNeuron'),
        ),
        migrations.AlterField(
            model_name='imagesettings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSettingsFromOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
