# Generated by Django 2.2.5 on 2019-10-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
    ]
