# Generated by Django 2.2.5 on 2019-10-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191024_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
