# Generated by Django 2.2.5 on 2019-10-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_project'),
        ('knox', '0007_auto_20190111_0542'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0003_projects_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
