# Generated by Django 2.2.5 on 2019-11-09 02:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brain_proto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='snb_s',
            fields=[
                ('brain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hearing_network.brain_proto')),
                ('_state', models.CharField(default='MISS?', max_length=280)),
                ('_index_ready_to_learn', models.IntegerField()),
                ('_last_learned_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RbfNeuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_has_knowledge', models.BooleanField()),
                ('_radius', models.FloatField()),
                ('_degraded', models.FloatField()),
                ('_knowledge', django.contrib.postgres.fields.jsonb.JSONField()),
                ('snb_sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbf_neurons', to='hearing_network.snb_s')),
            ],
        ),
        migrations.CreateModel(
            name='IndexRecognize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_recognize', models.IntegerField()),
                ('snb_sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_recognize', to='hearing_network.snb_s')),
            ],
        ),
    ]
