# Generated by Django 2.2.5 on 2019-11-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearing_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snb_s',
            name='brain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='snb_s', serialize=False, to='hearing_network.brain_proto'),
        ),
    ]
