# Generated by Django 2.2.5 on 2019-11-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearing_network', '0003_auto_20191109_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='snb_h',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_state', models.CharField(default='MISS?', max_length=280)),
                ('_index_ready_to_learn', models.IntegerField()),
                ('_last_learned_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='snb_s',
            name='brain',
        ),
        migrations.RenameField(
            model_name='rbfneuron',
            old_name='has_knowledge',
            new_name='_has_knowledge',
        ),
        migrations.RemoveField(
            model_name='indexrecognize',
            name='snb_sight',
        ),
        migrations.RemoveField(
            model_name='rbfneuron',
            name='snb_sight',
        ),
        migrations.DeleteModel(
            name='brain_proto',
        ),
        migrations.DeleteModel(
            name='snb_s',
        ),
        migrations.AddField(
            model_name='indexrecognize',
            name='snb_hearing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_recognize', to='hearing_network.snb_h'),
        ),
        migrations.AddField(
            model_name='rbfneuron',
            name='snb_hearing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbf_neurons', to='hearing_network.snb_h'),
        ),
    ]
