# Generated by Django 2.2.7 on 2019-12-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearing_network', '0004_auto_20191113_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbfneuron',
            name='snb_hearing',
        ),
        migrations.DeleteModel(
            name='IndexRecognize',
        ),
        migrations.DeleteModel(
            name='RbfNeuron',
        ),
        migrations.DeleteModel(
            name='snb_h',
        ),
    ]
