# Generated by Django 2.2.7 on 2019-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
