# Generated by Django 2.2.5 on 2019-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='go',
            field=models.IntegerField(default=0),
        ),
    ]
