# Generated by Django 2.2.5 on 2019-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_projects_go'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='go',
            new_name='brain_project_id',
        ),
    ]
