# Generated by Django 2.2.7 on 2019-12-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20191226_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brain',
            name='snb_s',
        ),
    ]
