# Generated by Django 2.2.5 on 2019-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_auto_20191025_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
