# Generated by Django 2.2.5 on 2019-11-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_auto_20191029_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
