# Generated by Django 2.2.5 on 2019-10-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_projects_projectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projectname',
            new_name='project_name',
        ),
    ]
