# Generated by Django 2.2.5 on 2019-11-13 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brain', '0004_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='brain_proto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snb_s', models.BinaryField()),
                ('snb_h', models.BinaryField()),
                ('rnb', models.BinaryField()),
                ('am_net', models.BinaryField()),
                ('gnb', models.BinaryField()),
                ('syllables_net', models.BinaryField()),
                ('word_net', models.BinaryField()),
                ('ss_rnb', models.BinaryField()),
                ('episodic_memory', models.BinaryField()),
                ('decisions_block', models.BinaryField()),
                ('internal_state', models.BinaryField()),
                ('desired_state', models.BinaryField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
