# Generated by Django 2.2.5 on 2019-11-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_brain_proto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain_proto',
            old_name='word_net',
            new_name='words_net',
        ),
    ]
