# Generated by Django 2.2.5 on 2019-11-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_auto_20191113_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain_proto',
            old_name='user_id',
            new_name='user',
        ),
    ]
