# Generated by Django 2.2.5 on 2019-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_auto_20191113_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain_proto',
            name='am_net',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='decisions_block',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='desired_state',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='episodic_memory',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='gnb',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='internal_state',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='rnb',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='snb_h',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='snb_s',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='ss_rnb',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='syllables_net',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='brain_proto',
            name='words_net',
            field=models.BinaryField(null=True),
        ),
    ]
